TEST DEFINITIONS AUTOMATIC TAGS ::= BEGIN

    TestInteger ::= SEQUENCE
    {
        integer             INTEGER
    }

    TestBoolean ::= SEQUENCE
    {
        boolean             BOOLEAN
    }

    TestPrintableString ::= SEQUENCE
    {
        string              PrintableString
    }

    TestEnumType ::= ENUMERATED
    {
        value0              (0),
        value1              (1),
        value2              (2)
    }

    TestEnum ::= SEQUENCE
    {
        enm                 TestEnumType
    }

    TestNested ::= SEQUENCE
    {
        nested              TestInteger
    }

    TestOptional ::= SEQUENCE
    {
        integer             INTEGER OPTIONAL,
        string              PrintableString OPTIONAL,
        boolean             BOOLEAN OPTIONAL
    }

END
