TEST DEFINITIONS AUTOMATIC TAGS ::= BEGIN

    TestInteger ::= SEQUENCE
    {
        integer             INTEGER
    }

    TestBoolean ::= SEQUENCE
    {
        boolean             BOOLEAN
    }

    TestNestedInteger ::= SEQUENCE
    {
        first               INTEGER,
        nested              TestInteger,
        last                INTEGER
    }

END
